name: predyktor-polmaratonu
services:
- name: web
  source_dir: /
  github:
    repo: JacaP30/ZADANIEDOMOWE9
    branch: main
  run_command: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: AWS_ACCESS_KEY_ID
    scope: RUN_TIME
    type: SECRET
  - key: AWS_SECRET_ACCESS_KEY
    scope: RUN_TIME
    type: SECRET
  - key: AWS_ENDPOINT_URL_S3
    scope: RUN_TIME
    type: SECRET
  http_port: 8501
