name: predyktor-polmaratonu
services:
  - name: backend
    source_dir: backend_fastapi
    github:
      repo: JacaP30/ZADANIEDOMOWE9
      branch: main
    run_command: uvicorn main:app --host 0.0.0.0 --port $PORT
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: PORT
        value: "8000"
      - key: OPENAI_API_KEY
        value: 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
        type: SECRET
      - key: AWS_ACCESS_KEY_ID
        value: DO003V2AYX9LCXW7RZYF
        type: SECRET
      - key: AWS_SECRET_ACCESS_KEY
        value: o3rCrvRaOAJrf8D7p0ULXPs3OkoUawZM121qAztiueM
        type: SECRET
      - key: AWS_ENDPOINT_URL_S3
        value: https://fra1.digitaloceanspaces.com
    http_port: 8000
    routes:
      - path: /
